name: Generate wakatime

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - output

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
